notifications:
  email:
    on_success: change
    on_failure: change
dist: xenial
sudo: false
language: python
cache: pip
python:
  - 3.6
  - 3.7
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
script:
  - py.test tests
