notifications:
  email:
    on_success: change
    on_failure: change
dist: trusty
sudo: false
language: python
cache: pip
python:
  - 3.6
    #  - 3.7 see https://github.com/travis-ci/travis-ci/issues/9815
install:
  - python setup.py develop
  - pip install -r dev_requirements.txt
script:
  - py.test --pylava